### ISSUE TITLE
M14 Loadouts

### ISSUE THREAD

**Issue by Teizan0** [Boberro/rof-loadout-issues#2]
I don't recall exactly some of the issues, but there's one big one for at least two of them:
There are no M14s in the M14 loadouts.

**Comment by Teizan0** [comment]
Additional: There was an overly Tacticool marksman rifle in the original loadout which can be replaced with an M14+Kahlia, and the M240(G?) with no barrel-shroud looks more like an M60 than the M240 with shroud.

**Comment by Boberro** [comment]
Riflemen have M14's in all M14 loadouts though...

**Comment by Boberro** [comment]
I changed MMG and DM. If you're still having issues with M14 loadouts, make sure you're loading it from the addon, not from mission file.
